### ISSUE TITLE
Missing dependency: `foreach` package

### ISSUE THREAD

**Issue by wassermann7** [dpuelz/BicliqueRT#15]
Hi BicliqueRT Authors!

Thanks for a great work preparing this package! I'm not a proficient R user, but I was trying to play around a bit with the package and I guess when you install it using `install_github("dpuelz/BicliqueRT")` command the required `foreach` package does not get installed and must be installed manually:

```
* installing *source* package ‘BicliqueRT’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘foreach’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘BicliqueRT’
```

Best regards!
Dawid

**Comment by dpuelz** [comment]
Hi @wassermann7, I'm glad you are checking out the package, and thanks for the feedback!  This should be fixed now.  Best, David
