### ISSUE TITLE
Regarding the size of the test

### ISSUE THREAD

**Issue by samzl1** [dpuelz/BicliqueRT#19]
Hi BicliqueRT Team,

Thank you for building this excellent package!

I'm playing around with the spatial interference code and running a 2000 simulation to check the size of the test. However, I consistently found the size of the test is much larger than 0.05.

For example, based on your current spatial interference code, I added the following at the bottom:

alpha = 0.05
sim_randomizations = 2e3

library(doParallel)
library(doRNG)

nCores <- 6   # number of CPUs for parallelization
cl<-makeCluster(nCores)
registerDoParallel(cl)
results.par.my <- foreach(i=1:sim_randomizations,.packages="BicliqueRT", .combine=rbind) %dorng% {
  
  Y = rnorm(N)
  
  results.par.my <- clique_test(Y, Z, Tstat, bd)$p.value
  
}

pp_my= colMeans(results.par.my<alpha)

stopCluster(cl)

The result for pp_my is 0.102, which implies a rejection rate of 10% under the null. Could you help double check what is causing this failure of the size control?

Best,
Liang

**Comment by dpuelz** [comment]
Hi @samzl1, thanks for raising this issue.  It has to do with one versus two-sided p-value calculations, and we've adjusted the way it's computed to remedy the problem.
